### ISSUE TITLE
What is the printing port of the zd220?

### ISSUE THREAD

**Issue by ewertonrfd** [SeTxNightDev/ZebraPrintAPI#1]
What is the printing port of the zd220?

![image](https://github.com/SeTxNightDev/ZebraPrintAPI/assets/13201575/dce89307-d5d9-4093-b71e-50e4492aabba)

I tried the 9100 but it didn't do anything yet

Att

**Comment by SeTxNightDev** [comment]
Hey,
the port is 9100, but you need to connect the Printer with network cable to use the API.
